/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/companies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar Empresas */
    get: operations["listar_empresas_companies_get"];
    put?: never;
    /** Criar Empresa */
    post: operations["criar_empresa_companies_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/companies/{company_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obter Empresa */
    get: operations["obter_empresa_companies__company_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Atualizar Empresa */
    patch: operations["atualizar_empresa_companies__company_id__patch"];
    trace?: never;
  };
  "/companies/{company_id}/movements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar Movimentos */
    get: operations["listar_movimentos_companies__company_id__movements_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/companies/{company_id}/movements/{competencia}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Lancar Movimento */
    put: operations["lancar_movimento_companies__company_id__movements__competencia__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/companies/{company_id}/fator-r": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fator R Da Empresa */
    get: operations["fator_r_da_empresa_companies__company_id__fator_r_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Carteira */
    get: operations["carteira_portfolio_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/observability/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resumo Observabilidade */
    get: operations["resumo_observabilidade_observability_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/traces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar Traces */
    get: operations["listar_traces_traces_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/traces/{trace_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detalhe Trace */
    get: operations["detalhe_trace_traces__trace_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/traces/{trace_id}/human-eval": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Avaliar Trace */
    post: operations["avaliar_trace_traces__trace_id__human_eval_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inbox/pgdas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enviar Extrato */
    post: operations["enviar_extrato_inbox_pgdas_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inbox": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar Documentos */
    get: operations["listar_documentos_inbox_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inbox/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obter Documento */
    get: operations["obter_documento_inbox__document_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inbox/{document_id}/arquivo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Baixar Original */
    get: operations["baixar_original_inbox__document_id__arquivo_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inbox/{document_id}/link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Vincular Documento */
    post: operations["vincular_documento_inbox__document_id__link_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inbox/{document_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rejeitar Documento */
    post: operations["rejeitar_documento_inbox__document_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/companies/{company_id}/simulations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Historico Simulacoes */
    get: operations["historico_simulacoes_companies__company_id__simulations_get"];
    put?: never;
    /** Simular Empresa */
    post: operations["simular_empresa_companies__company_id__simulations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agents/consultor/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Conversar Consultor */
    post: operations["conversar_consultor_agents_consultor_chat_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agents/priorizador/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Conversar Priorizador */
    post: operations["conversar_priorizador_agents_priorizador_chat_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agents/echo/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rodar Echo */
    post: operations["rodar_echo_agents_echo_run_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AgentOut */
    AgentOut: {
      /** Texto */
      texto: string;
      /** Decisao */
      decisao: {
        [key: string]: unknown;
      };
      /** Trace Id */
      trace_id: string;
    };
    /** Body_enviar_extrato_inbox_pgdas_post */
    Body_enviar_extrato_inbox_pgdas_post: {
      /** Arquivo */
      arquivo: string;
    };
    /** CarteiraOut */
    CarteiraOut: {
      /** Pa */
      pa: string;
      kpis: components["schemas"]["KpisOut"];
      /** Linhas */
      linhas: components["schemas"]["LinhaCarteiraOut"][];
    };
    /** CompanyIn */
    CompanyIn: {
      /** Nome */
      nome: string;
      /** Cnpj */
      cnpj: string;
      /** Cnae */
      cnae?: string | null;
      /** Atividade */
      atividade?: string | null;
      /** Sujeita Fator R */
      sujeita_fator_r: boolean;
      /**
       * Qtd Socios
       * @default 1
       */
      qtd_socios?: number;
      /** Contato */
      contato?: string | null;
      /** Pacote */
      pacote?: ("monitoramento" | "correcao" | "retainer") | null;
      /**
       * Honorario Mensal
       * @default 0
       */
      honorario_mensal?: number | string;
      /**
       * Ativo
       * @default true
       */
      ativo?: boolean;
      /** Notas */
      notas?: string | null;
      /** Inicio Atividade */
      inicio_atividade?: string | null;
    };
    /** CompanyList */
    CompanyList: {
      /** Items */
      items: components["schemas"]["CompanyOut"][];
      /** Total */
      total: number;
    };
    /** CompanyOut */
    CompanyOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Nome */
      nome: string;
      /** Cnpj */
      cnpj: string;
      /** Cnpj Formatado */
      cnpj_formatado: string;
      /** Cnae */
      cnae: string | null;
      /** Atividade */
      atividade: string | null;
      /** Sujeita Fator R */
      sujeita_fator_r: boolean;
      /** Qtd Socios */
      qtd_socios: number;
      /** Contato */
      contato: string | null;
      /** Pacote */
      pacote: ("monitoramento" | "correcao" | "retainer") | null;
      /** Honorario Mensal */
      honorario_mensal: string;
      /** Ativo */
      ativo: boolean;
      /** Notas */
      notas: string | null;
      /** Inicio Atividade */
      inicio_atividade: string | null;
    };
    /** CompanyPatch */
    CompanyPatch: {
      /** Nome */
      nome?: string | null;
      /** Cnpj */
      cnpj?: string | null;
      /** Cnae */
      cnae?: string | null;
      /** Atividade */
      atividade?: string | null;
      /** Sujeita Fator R */
      sujeita_fator_r?: boolean | null;
      /** Qtd Socios */
      qtd_socios?: number | null;
      /** Contato */
      contato?: string | null;
      /** Pacote */
      pacote?: ("monitoramento" | "correcao" | "retainer") | null;
      /** Honorario Mensal */
      honorario_mensal?: number | string | null;
      /** Ativo */
      ativo?: boolean | null;
      /** Notas */
      notas?: string | null;
      /** Inicio Atividade */
      inicio_atividade?: string | null;
    };
    /** ConsultorIn */
    ConsultorIn: {
      /** Mensagem */
      mensagem: string;
      /** Company Id */
      company_id?: string | null;
    };
    /** DocumentoList */
    DocumentoList: {
      /** Items */
      items: components["schemas"]["DocumentoOut"][];
      /** Total */
      total: number;
      /** Contagem Por Status */
      contagem_por_status: {
        [key: string]: number;
      };
    };
    /** DocumentoOut */
    DocumentoOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Texto Agente */
      texto_agente?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "received" | "parsed" | "needs_review" | "linked" | "rejected";
      /** Motivo */
      motivo: string | null;
      /** Company Id */
      company_id: string | null;
      /** Nome Original */
      nome_original: string | null;
      /**
       * Mime
       * @enum {string}
       */
      mime: "application/pdf" | "text/plain";
      /** Tamanho Bytes */
      tamanho_bytes: number;
      /** Campos */
      campos: {
        [key: string]: unknown;
      };
      /** Confianca */
      confianca: string | null;
      /** Parser Version */
      parser_version: string | null;
      /** Trace Id */
      trace_id: string;
      /**
       * Criado Em
       * Format: date-time
       */
      criado_em: string;
    };
    /** EchoIn */
    EchoIn: {
      /** Mensagem */
      mensagem: string;
    };
    /** EvalHumanaOut */
    EvalHumanaOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Nota
       * @enum {string}
       */
      nota: "acerto" | "parcial" | "erro";
      /** Comentario */
      comentario: string | null;
      /**
       * Criado Em
       * Format: date-time
       */
      criado_em: string;
    };
    /** EvalOuroOut */
    EvalOuroOut: {
      /** Campo */
      campo: string;
      /** Esperado */
      esperado: string | null;
      /** Obtido */
      obtido: string | null;
      /** Dentro Tolerancia */
      dentro_tolerancia: boolean | null;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "erro" | "ouro_indisponivel";
    };
    /** FatorROut */
    FatorROut: {
      /** Pa */
      pa: string;
      /** Janela Inicio */
      janela_inicio: string;
      /** Janela Fim */
      janela_fim: string;
      /** Meses Preenchidos */
      meses_preenchidos: string[];
      /** Meses Faltantes */
      meses_faltantes: string[];
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "dados_insuficientes";
      /** Motivo */
      motivo:
        ("rbt12_zero" | "empresa_nova_regra_pendente" | "rbt12_acima_do_limite_do_simples") | null;
      /** Rbt12 */
      rbt12: string;
      /** Fs12 */
      fs12: string;
      /** Fator R */
      fator_r: string | null;
      /** Anexo */
      anexo: ("III" | "V") | null;
      /** Semaforo */
      semaforo: ("vermelho" | "amarelo" | "verde") | null;
      /** Folha Minima 28 */
      folha_minima_28: string | null;
      /** Folha Minima Meta */
      folha_minima_meta: string | null;
      /** Gap 12M 28 */
      gap_12m_28: string | null;
      /** Reforco Mensal 28 */
      reforco_mensal_28: string | null;
      /** Gap 12M Meta */
      gap_12m_meta: string | null;
      /** Reforco Mensal Meta */
      reforco_mensal_meta: string | null;
      /** Aliquota Efetiva Iii */
      aliquota_efetiva_iii: string | null;
      /** Aliquota Efetiva V */
      aliquota_efetiva_v: string | null;
      /** Economia 12M */
      economia_12m: string | null;
      /** Meta Operacional */
      meta_operacional: string;
      /** Cpp Integra Fs12 */
      cpp_integra_fs12: boolean;
      /**
       * Tabela Vigencia Inicio
       * Format: date
       */
      tabela_vigencia_inicio: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** KpisOut */
    KpisOut: {
      /** Monitoradas */
      monitoradas: number;
      /** No V */
      no_v: number;
      /** No Limite */
      no_limite: number;
      /** Seguras */
      seguras: number;
      /** Dados Insuficientes */
      dados_insuficientes: number;
      /** Economia Em Jogo */
      economia_em_jogo: string;
      /** Honorarios Pacotes */
      honorarios_pacotes: string;
    };
    /** LinhaCarteiraOut */
    LinhaCarteiraOut: {
      /**
       * Company Id
       * Format: uuid
       */
      company_id: string;
      /** Nome */
      nome: string;
      /** Cnpj Formatado */
      cnpj_formatado: string;
      /** Pacote */
      pacote: ("monitoramento" | "correcao" | "retainer") | null;
      /** Honorario Mensal */
      honorario_mensal: string;
      /**
       * Acao
       * @enum {string}
       */
      acao: "reuniao_correcao" | "vigiar_simular" | "manter" | "completar_lancamentos";
      /** Acao Texto */
      acao_texto: string;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "dados_insuficientes";
      /** Motivo */
      motivo: string | null;
      /** Semaforo */
      semaforo: ("vermelho" | "amarelo" | "verde") | null;
      /** Fator R */
      fator_r: string | null;
      /** Anexo */
      anexo: ("III" | "V") | null;
      /** Rbt12 */
      rbt12: string;
      /** Fs12 */
      fs12: string;
      /** Reforco Mensal 28 */
      reforco_mensal_28: string | null;
      /** Reforco Mensal Meta */
      reforco_mensal_meta: string | null;
      /** Economia 12M */
      economia_12m: string | null;
      /** Meses Faltantes */
      meses_faltantes: string[];
    };
    /** LoginIn */
    LoginIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Senha */
      senha: string;
    };
    /** MeOut */
    MeOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Firm Id
       * Format: uuid
       */
      firm_id: string;
      /** Email */
      email: string;
      /** Nome */
      nome: string;
    };
    /** MovementIn */
    MovementIn: {
      /**
       * Receita Bruta
       * @default 0
       */
      receita_bruta?: number | string;
      /**
       * Pro Labore
       * @default 0
       */
      pro_labore?: number | string;
      /**
       * Salarios
       * @default 0
       */
      salarios?: number | string;
      /**
       * Cpp
       * @default 0
       */
      cpp?: number | string;
      /**
       * Fgts
       * @default 0
       */
      fgts?: number | string;
      /** Observacao */
      observacao?: string | null;
    };
    /** MovementOut */
    MovementOut: {
      /** Competencia */
      competencia: string;
      /** Receita Bruta */
      receita_bruta: string;
      /** Pro Labore */
      pro_labore: string;
      /** Salarios */
      salarios: string;
      /** Cpp */
      cpp: string;
      /** Fgts */
      fgts: string;
      /** Folha Mes */
      folha_mes: string;
      /**
       * Origem
       * @enum {string}
       */
      origem: "manual" | "pgdas" | "folha" | "agente";
      /** Observacao */
      observacao: string | null;
      /** Pgdas Document Id */
      pgdas_document_id: string | null;
    };
    /** NotaHumanaIn */
    NotaHumanaIn: {
      /**
       * Nota
       * @enum {string}
       */
      nota: "acerto" | "parcial" | "erro";
      /** Comentario */
      comentario?: string | null;
    };
    /** PriorizadorIn */
    PriorizadorIn: {
      /** Mensagem */
      mensagem: string;
      /** Pa */
      pa?: string | null;
    };
    /** RejeicaoIn */
    RejeicaoIn: {
      /** Motivo */
      motivo: string;
    };
    /** RespostaAgente */
    RespostaAgente: {
      /** Texto */
      texto: string;
      /** Decisao */
      decisao: {
        [key: string]: unknown;
      };
      /** Trace Id */
      trace_id: string;
    };
    /** ResumoAgenteOut */
    ResumoAgenteOut: {
      /** Agente */
      agente: string;
      /** Volume */
      volume: number;
      /** Latencia Media Ms */
      latencia_media_ms: string | null;
      /** Confianca Media */
      confianca_media: string | null;
      /** Erros */
      erros: number;
      /** Reviews */
      reviews: number;
    };
    /** ResumoOut */
    ResumoOut: {
      /** Corridas 24H */
      corridas_24h: number;
      /** Corridas Total */
      corridas_total: number;
      /** Pendencias Sem Nota */
      pendencias_sem_nota: number;
      /** Acerto Ouro */
      acerto_ouro: string | null;
      /** Acerto Humano */
      acerto_humano: string | null;
      /** Por Agente */
      por_agente: components["schemas"]["ResumoAgenteOut"][];
      /** Custo Llm 30D */
      custo_llm_30d: string | null;
      /** Tokens Llm 30D */
      tokens_llm_30d: number | null;
    };
    /** SimulacaoIn */
    SimulacaoIn: {
      /**
       * Pa
       * @example 2026-09
       */
      pa: string;
      /** Meta */
      meta?: number | string | null;
      /**
       * Fracao Pro Labore
       * @default 1
       */
      fracao_pro_labore?: number | string;
      /**
       * Inss
       * @default 0.11
       */
      inss?: number | string;
      /**
       * Irrf
       * @default 0.275
       */
      irrf?: number | string;
      /**
       * Horizonte Meses
       * @default 12
       */
      horizonte_meses?: number;
    };
    /** SimulacaoOut */
    SimulacaoOut: {
      /**
       * Simulation Id
       * Format: uuid
       */
      simulation_id: string;
      /** Trace Id */
      trace_id: string;
      /** Pa */
      pa: string;
      /** Veredito */
      veredito: ("ja_na_meta" | "corrigir" | "nao_forcar") | null;
      /** Texto */
      texto: string;
      /** Parametros */
      parametros: {
        [key: string]: unknown;
      };
      /** Resultado */
      resultado: {
        [key: string]: unknown;
      };
      /** Criado Em */
      criado_em?: string | null;
    };
    /** SpanOut */
    SpanOut: {
      /** Id */
      id: string;
      /** Nome */
      nome: string;
      /** Tipo */
      tipo: string;
      /** Inicio */
      inicio: string | null;
      /** Fim */
      fim: string | null;
      /** Latencia Ms */
      latencia_ms: number | null;
      /** Nivel */
      nivel: string | null;
      /** Parent Id */
      parent_id: string | null;
      /** Modelo */
      modelo: string | null;
      /** Custo */
      custo: number | null;
    };
    /** TraceDetalheOut */
    TraceDetalheOut: {
      trace: components["schemas"]["TraceResumoOut"];
      /** Entrada */
      entrada: {
        [key: string]: unknown;
      };
      /** Saida */
      saida: {
        [key: string]: unknown;
      };
      /** Decisao */
      decisao: {
        [key: string]: unknown;
      };
      /** Spans */
      spans: components["schemas"]["SpanOut"][];
      /** Spans Indisponiveis */
      spans_indisponiveis: boolean;
      /** Evals Ouro */
      evals_ouro: components["schemas"]["EvalOuroOut"][];
      /** Evals Humanas */
      evals_humanas: components["schemas"]["EvalHumanaOut"][];
      /** Langfuse Url */
      langfuse_url: string;
    };
    /** TraceList */
    TraceList: {
      /** Items */
      items: components["schemas"]["TraceResumoOut"][];
      /** Total */
      total: number;
    };
    /** TraceResumoOut */
    TraceResumoOut: {
      /** Id */
      id: string;
      /** Agente */
      agente: string;
      /** Gatilho */
      gatilho: string;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "error" | "needs_review";
      /** Confianca */
      confianca: string | null;
      /** Latencia Ms */
      latencia_ms: number | null;
      /**
       * Langfuse Sync
       * @enum {string}
       */
      langfuse_sync: "pending" | "ok" | "failed";
      /** Company Id */
      company_id: string | null;
      /**
       * Criado Em
       * Format: date-time
       */
      criado_em: string;
      /** Tem Nota Humana */
      tem_nota_humana: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VinculoIn */
    VinculoIn: {
      /**
       * Company Id
       * Format: uuid
       */
      company_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeOut"];
        };
      };
    };
  };
  listar_empresas_companies_get: {
    parameters: {
      query?: {
        ativo?: boolean | null;
        sujeita_fator_r?: boolean | null;
        busca?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  criar_empresa_companies_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  obter_empresa_companies__company_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  atualizar_empresa_companies__company_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  listar_movimentos_companies__company_id__movements_get: {
    parameters: {
      query?: {
        de?: string | null;
        ate?: string | null;
      };
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MovementOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  lancar_movimento_companies__company_id__movements__competencia__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        company_id: string;
        competencia: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MovementIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MovementOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  fator_r_da_empresa_companies__company_id__fator_r_get: {
    parameters: {
      query?: {
        pa?: string | null;
      };
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FatorROut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  carteira_portfolio_get: {
    parameters: {
      query?: {
        pa?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CarteiraOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resumo_observabilidade_observability_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResumoOut"];
        };
      };
    };
  };
  listar_traces_traces_get: {
    parameters: {
      query?: {
        agente?: string | null;
        status?: ("ok" | "error" | "needs_review") | null;
        sem_nota?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TraceList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detalhe_trace_traces__trace_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TraceDetalheOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  avaliar_trace_traces__trace_id__human_eval_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NotaHumanaIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EvalHumanaOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  enviar_extrato_inbox_pgdas_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_enviar_extrato_inbox_pgdas_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentoOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  listar_documentos_inbox_get: {
    parameters: {
      query?: {
        status?: ("received" | "parsed" | "needs_review" | "linked" | "rejected") | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentoList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  obter_documento_inbox__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentoOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  baixar_original_inbox__document_id__arquivo_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  vincular_documento_inbox__document_id__link_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VinculoIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentoOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rejeitar_documento_inbox__document_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejeicaoIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentoOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  historico_simulacoes_companies__company_id__simulations_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SimulacaoOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  simular_empresa_companies__company_id__simulations_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SimulacaoIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SimulacaoOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  conversar_consultor_agents_consultor_chat_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsultorIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RespostaAgente"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  conversar_priorizador_agents_priorizador_chat_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PriorizadorIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RespostaAgente"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rodar_echo_agents_echo_run_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EchoIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
